version: '2'
services:
  web:
    image: maxbey/schedule-backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - SECRET_KEY=somesecretvalue
      - DJANGO_CONFIGURATION=Production
      - DJANGO_SETTINGS_MODULE=app.settings.settings
    ports:
      - "8000:8000"
    volumes:
      - ./schedule/static:/usr/src/app/static
    expose:
      - "8000"

  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"